import { StyleSheet, Text, TextInput, View } from 'react-native';
import { MessageSquareText, ShieldCheck } from 'lucide-react-native';
import type { AppLocale } from '../../onboarding/preferences';
import type { LessonContent } from '../data/lessonCatalog';
import { colors, fonts, radius, spacing } from '../../../theme/tokens';

type Props = { lesson: LessonContent; locale: AppLocale; onChange: (value: string) => void; value: string };

export function ProduceStage({ lesson, locale, onChange, value }: Props) {
  const remaining = Math.max(0, lesson.production.minimumCharacters - value.trim().length);
  return <View style={styles.stage}><View style={styles.heading}><View style={styles.icon}><MessageSquareText color={colors.primary} size={25} /></View><View style={styles.headingCopy}><Text style={styles.eyebrow}>{locale === 'fr' ? 'CRÉEZ VOS PROPRES PHRASES' : 'CREATE YOUR OWN SENTENCES'}</Text><Text style={styles.title}>{locale === 'fr' ? 'À vous de produire' : 'Your turn to produce'}</Text></View></View><Text style={styles.prompt}>{lesson.production.prompt}</Text><TextInput accessibilityLabel={locale === 'fr' ? 'Votre réponse en anglais' : 'Your answer in English'} autoCapitalize="sentences" multiline onChangeText={onChange} placeholder={lesson.production.placeholder} placeholderTextColor={colors.textMuted} style={styles.input} textAlignVertical="top" value={value} /><Text accessibilityLiveRegion="polite" style={styles.counter}>{remaining > 0 ? (locale === 'fr' ? `Encore ${remaining} caractères minimum` : `${remaining} more characters required`) : (locale === 'fr' ? 'Réponse prête à envoyer' : 'Answer ready to send')}</Text><View style={styles.privacyNote}><ShieldCheck color={colors.success} size={21} /><Text style={styles.privacyText}>{locale === 'fr' ? 'L’évaluation IA est effectuée côté serveur. Aucune clé ni logique de modèle n’est exposée dans l’application.' : 'AI evaluation runs on the server. No model key or model logic is exposed in the app.'}</Text></View></View>;
}

const styles = StyleSheet.create({ stage: { gap: spacing.xl }, heading: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.md }, icon: { alignItems: 'center', backgroundColor: colors.primarySoft, borderRadius: radius.pill, height: 48, justifyContent: 'center', width: 48 }, headingCopy: { flex: 1, gap: spacing.xs }, eyebrow: { color: colors.primary, fontFamily: fonts.semibold, fontSize: 11, letterSpacing: 0.8 }, title: { color: colors.text, fontFamily: fonts.bold, fontSize: 28 }, prompt: { color: colors.text, fontFamily: fonts.medium, fontSize: 18, lineHeight: 28 }, input: { backgroundColor: colors.surface, borderColor: colors.outline, borderRadius: radius.lg, borderWidth: 1, color: colors.text, fontFamily: fonts.regular, fontSize: 17, lineHeight: 27, minHeight: 180, padding: spacing.lg }, counter: { color: colors.textMuted, fontFamily: fonts.medium, fontSize: 12, textAlign: 'right' }, privacyNote: { alignItems: 'flex-start', backgroundColor: colors.successSoft, borderRadius: radius.lg, flexDirection: 'row', gap: spacing.md, padding: spacing.lg }, privacyText: { color: colors.textMuted, flex: 1, fontFamily: fonts.regular, fontSize: 13, lineHeight: 20 } });
